---
gitLabUrl: http://gitlab.imshealthcloud.net
gitLabUsername: root
gitLabPassword: ""
gitLabPrivateToken: CuXYXmXmSiSMjGiY2VKx
jenkinsUrl: http://jenkins.imshealthcloud.net/service/jenkins
jenkinsUserName: jreagor-admin
jenkinsPassword: B2SK3oSMTykNR"0+n7+VL4OgB
