---
  gitLaburl:
    description: "FQDN to gitLab"
    type: "string"
    secret: false
    required: true
  gitLabusername:
    description: "gitLab Username (if auth is enabled)"
    type: "string"
    secret: false
    required: false
  gitLabpassword:
    description: "gitLab Password (if auth is enabled)"
    type: "string"
    secret: true
    required: false
