---
  url:
    description: "FQDN to gitLab"
    type: "string"
    secret: false
    required: true
  username:
    description: "gitLab Username (if auth is enabled)"
    type: "string"
    secret: false
    required: false
  password:
    description: "gitLab Password (if auth is enabled)"
    type: "string"
    secret: true
    required: false
